### ISSUE TITLE
new version of pg_dump makes a partition via two statements

### ISSUE THREAD

**Issue by antonov-impulsm** [polymorphm/pg-dump-splitter#8]
example:

```
CREATE TABLE traffic_face_var.tf_checks_part63 (
    tf_check_id bigint NOT NULL,
    creat_datetime timestamp with time zone NOT NULL,
    camera text NOT NULL,
    time_check timestamp without time zone NOT NULL,
    face_media_id bigint,
    overview_media_id bigint,
    additional json,
    vendor text,
    vn_candidates traffic_face_typ.vn_candidate[],
    camera_id bigint,
    latitude numeric,
    longitude numeric,
    azimuth numeric,
    descr_versions text[],
    descrs bytea[],
    error_state integer,
    recov_datetime timestamp with time zone,
    fired_vn_candidates traffic_face_typ.vn_candidate[],
    source_code integer
);
ALTER TABLE ONLY traffic_face_var.tf_checks ATTACH PARTITION traffic_face_var.tf_checks_part63 FOR VALUES FROM ('2018-07-01 00:00:00') TO ('2018-08-01 00:00:00');
```

and the issue is -- the second statement ``ALTER TABLE ONLY traffic_face_var.tf_checks ATTACH PARTITION traffic_face_var.tf_checks_part63 ...`` ***SHOULD*** be with partition table (not be with root table).

current ``pg-dump-splitter`` rules makes (wrong) it with root table considering as a regular ``ALTER TABLE ...`` rule. it makes problems with filtering in automating scripts.

```
$ pg_dump -V
pg_dump (PostgreSQL) 11.4
```

------------------------------------------------------------

the logic of ``pg_dump ... -ttraffic_face_var.tf_checks_part63`` does agree with this issue. ``pg-dump-splitter`` should correct its rules.

**Comment by polymorphm** [comment]
it has been fixed in: b108caf3a , 51fb9607e

but obviously still there is problem with Partitioned Indexes (since PG11), because we have no alter-rule for indexed yet at all. I'll open detached issue for indexes!
